### ISSUE TITLE
Testing data from toolboxes

### ISSUE THREAD

**Issue by rob-luke** [BUNPC/pysnirf2#16]
Just an FYI. I maintain a set of test data from different vendors and software at https://github.com/mne-tools/mne-testing-data/tree/master/SNIRF  I will try and add more test data as software packages change their implementation and more vendors use snirf. Please feel free to use this data too.

This probably isn't useful as official test data for you here, as some of them aren't actually compliant. But thought it could come in handy for your local testing.

**Comment by sstucker** [comment]
Thanks, I can build some tests around these
