### ISSUE TITLE
Conversion (Homer3) .nirs to .snirf validation 

### ISSUE THREAD

**Issue by EwanMahe** [BUNPC/pysnirf2#36]
Hello everyone, 

I have a question concerning the validation of the format of a .snirf file on Python. I convert a .nirs file to a .snirf file via Homer3 (v.1.71.1). When I use the validateSnirf() function, then result.display() to check the validity of this converted .snirf file, I get 120 WARNING and 2 FATAL (for dataTimeSeries for example). I don't understand because the file is supposed to be converted by Homer3, so I thought it would be valid, without errors. Does anyone know where this problem comes from, is it a problem with Homer3 (the file converted by Homer3 would not respect the specifications of the .snirf format) or with the validateSnirf function of Python? This may be a mistake on my part, as I am not an expert in this area. Sorry if the problem is obvious, or if it has already been solved previously.

Thanks in advance for your time and your help.

Ewan Mahé

**Comment by sstucker** [comment]
See my response to https://github.com/fNIRS/snirf/issues/134.
